<div class="no-map-content">
    <img style="margin: 30px 0 5px 0;" src="images/logo-about.png">

    <p style="margin: 30px 0; font-size: 26px;">
        Website for storage and exchange of environmental monitoring metadata
    </p>
    
    <p style="margin-bottom: 20px; font-size: 15px;">
        &copy; 2023
        <a href="https://www.ih.cas.cz/" target="_blank" style="color: var(--color-blue); font-weight: bold;">
            Institute of Hydrodynamics of the CAS
        </a>
    </p>
    
    <p style="font-size: 14px;">The development is supported by <a class="reference" href='https://strategie.avcr.cz/' target='_blank'>Strategy AV21</a></p>
    
    <div class="about-image-panel">
        <a href='https://www.avcr.cz' target='_blank' title='Czech Academy of Sciences'><img src='images/logo_avcr.png'/></a>
        <a style="margin-top: 10px;" href='https://strategie.avcr.cz/' target='_blank' title='Strategy AV21'><img src='images/logo_strategie.png'/></a>
    </div>
    
    <div class="additional-info">
        <p>This website uses only necessary cookies.</p>
        <p>By using this website you declare your consent whith the cookies.</p>
        
        <br>
        
        <p class="browsers">
            Designed for
            <img src="images/logo-firefox.png" title="Mozilla Firefox">
            <img src="images/logo-chrome.png" title="Google Chrome">
            <img src="images/logo-opera.png" title="Opera">
            <img src="images/logo-edge.png" title="Microsoft Edge">
        </p>
        
        <br>
        
        <p>This website uses icons by <a class="reference" href="https://www.flaticon.com" target="_blank">Flaticon</a></p>
    </div>
    
</div>

