<div class="no-map-content">
    <h1>Login</h1>
    <form method="post">
        <div class="label">E-mail*</div>
        <input type="email" name="email" required="required" value="<?= $email ?>"/>
        
        <div class="label">Password*</div>
        <input type="password" name="password" required="required" />
        
        <br>
        <input class="button" type="submit" value="Login" />
    </form>
    
    <div class="admin-info">
        <p>To get an account please contact admin:</p>
        <p class="admin-mail-info">hnilica(at)ih.cas.cz</p>
        <p class="admin-mail-info">sipek(at)ih.cas.cz</p>
    </div>
</div>

