<div class="no-map-content">
    <h1>New user</h1>
    
    <form method="post">
        <div class="label">Name*</div>
        <input type="text" name="jmeno" required="required" value="<?php $this->printValueIfExists($formData, "jmeno"); ?>"/>
        
        <div class="label">E-mail*</div>
        <input type="email" name="email" required="required" value="<?php $this->printValueIfExists($formData, "email"); ?>"/>
        
        <div class="label">Password*</div>
        <input type="text" name="heslo" required="required" value="<?php $this->printValueIfExists($formData, "heslo"); ?>"/>
        
        <div class="label">Institution*</div>
        <select name="id_instituce">
            <?php
                if (!key_exists("id_instituce", $formData))
                    $formData["id_instituce"] = null;
                $this->printSelectOptions($institutions, "id_instituce", "nazev", $formData["id_instituce"]);
            ?>
        </select>
        
        <div class="label">Admin*</div>
        <select name="admin">
            <option value="0">No</option>
            <option value="1">yes</option>
        </select>
        
        <br>
        <input class="button" type="submit" value="Save" />
    </form>
</div>


